#pragma once
#include "precompiled_header.h"

#include "AI/neuralNetworks/neuralNetwork.h"
#include "AI/neuralNetworks/neuralNetworkTraining.h"
#include "applications/applicationDevelopment.h"
#include "audio/audioSample.h"
#include "core/archiveData.h"
#include "core/log.h"
#include "core/settings.h"
#include "core/singleton.h"
#include "core/system.h"
#include "core/timing.h"
#include "core/utils.h"
#include "graphics/colour.h"
#include "graphics/image.h"
#include "graphics/imagePacker.h"
#include "graphics/renderDevice.h"
#include "graphics/renderTexture.h"
#include "graphics/shader.h"
#include "graphics/sprites/spriteDescription.h"
#include "graphics/sprites/spriteEntity.h"
#include "graphics/sprites/spriteLayer.h"
#include "graphics/sprites/sprites.h"
#include "graphics/textFont.h"
#include "graphics/texture.h"
#include "graphics/vertexBuffer.h"
#include "gui/gui_button.h"
#include "gui/gui_linegraph.h"
#include "gui/gui_theme.h"
#include "gui/gui_window.h"
#include "input/inputJoystick.h"
#include "input/inputKeyboard.h"
#include "input/inputMouse.h"
#include "managers/managerApplications.h"
#include "managers/managerArchives.h"
#include "managers/managerAudio.h"
#include "managers/managerGUI.h"
#include "managers/managerInputDevices.h"
#include "managers/managerRenderTextures.h"
#include "managers/managerShaders.h"
#include "managers/managerSprites.h"
#include "managers/managerTextFonts.h"
#include "managers/managerTextures.h"
#include "math/line2d.h"
#include "math/matrix.h"
#include "math/quaternion.h"
#include "math/rect2d.h"
#include "math/vector2.h"
#include "math/vector3.h"
#include "math/vector4.h"

namespace Nexus
{

}